server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: true
    change-log: classpath:/db/hexagonal/db.changelog-master.xml

  datasource:
    url: jdbc:h2:mem:hexagonal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  messages:
    basename: i18n/messages

  resources:
    add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true

  redis:
    host: "127.0.0.1"
    port: 6379
    database: 2

  servlet:
    multipart:
      max-request-size: 32MB
